import Link from 'next/link';
import { ArrowRight, BookOpen, Bot, Users, Video } from 'lucide-react';
import { getHomepageData } from '@/lib/data';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';

export default async function HomePage() {
  const { courses, webinars, articles, botFeatures } = await getHomepageData();
  const audience = ['Подростки 12–17 лет', 'Студенты и молодые специалисты 18–30 лет', 'Взрослые 30–45 лет'];
  return <>
    <section className="section bg-[radial-gradient(circle_at_top,_rgba(59,130,246,0.15),_transparent_40%)]"><div className="container-page grid items-center gap-10 lg:grid-cols-2"><div><Badge>EdTech + FinTech</Badge><h1 className="mt-4 text-5xl font-black tracking-tight text-slate-950">FinSkills Pro — финансовая грамотность для жизни.</h1><p className="mt-5 max-w-2xl text-lg text-slate-600">Курсы, вебинары, тесты и образовательный Telegram-ассистент, который помогает выстроить здоровые финансовые привычки без обещаний быстрой прибыли.</p><div className="mt-8 flex gap-3"><Link href="/auth/register"><Button>Начать обучение</Button></Link><Link href="/courses"><Button variant="outline">Посмотреть курсы</Button></Link></div></div><Card className="card-gradient p-8"><div className="grid gap-4 sm:grid-cols-2">{[['Курсы', '9+ модулей'], ['Вебинары', 'Живые встречи'], ['Квизы', 'После каждого урока'], ['Ассистент', 'Напоминания и подсказки']].map(([a,b]) => <div key={a} className="rounded-2xl bg-white p-5"><p className="font-semibold">{a}</p><p className="mt-2 text-sm text-slate-600">{b}</p></div>)}</div></Card></div></section>
    <section className="section"><div className="container-page"><h2 className="text-3xl font-bold">Для кого платформа</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{audience.map((item) => <Card key={item} className="p-6"><Users className="text-blue-600" /><h3 className="mt-4 font-semibold">{item}</h3><p className="mt-2 text-sm text-slate-600">Персонализированные программы под возраст и жизненные задачи.</p></Card>)}</div></div></section>
    <section className="section bg-white"><div className="container-page"><h2 className="text-3xl font-bold">Как работает платформа</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{[{icon:BookOpen,title:'Курсы',text:'Видео, тексты и тесты по бюджету, инфляции, налогам и инвестициям.'},{icon:Bot,title:'Telegram-бот',text:'Напоминания, учебные сводки и ответы на популярные вопросы.'},{icon:Video,title:'Онлайн-уроки',text:'Вебинары со специалистами и разбор практических кейсов.'}].map((item)=> <Card key={item.title} className="p-6"><item.icon className="text-emerald-500" /><h3 className="mt-4 text-xl font-semibold">{item.title}</h3><p className="mt-2 text-slate-600">{item.text}</p></Card>)}</div></div></section>
    <section className="section"><div className="container-page grid gap-6 lg:grid-cols-3">{courses.map((course) => <Card key={course.id} className="overflow-hidden"><div className="h-40 bg-gradient-to-r from-blue-600 to-emerald-500" /><div className="p-6"><h3 className="text-xl font-semibold">{course.title}</h3><p className="mt-2 text-sm text-slate-600">{course.description}</p><Link href={`/courses/${course.slug}`} className="mt-4 inline-flex items-center text-sm font-semibold text-blue-600">Открыть курс <ArrowRight className="ml-1 h-4 w-4" /></Link></div></Card>)}</div></section>
    <section className="section bg-slate-950 text-white"><div className="container-page grid gap-6 md:grid-cols-2 lg:grid-cols-4">{botFeatures.map((item)=> <div key={item.id}><h3 className="font-semibold">{item.title}</h3><p className="mt-2 text-sm text-slate-300">{item.description}</p></div>)}</div></section>
    <section className="section"><div className="container-page grid gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-bold">Отзывы</h2><div className="mt-6 space-y-4">{['Теперь я понимаю, как вести бюджет и копить на цели.', 'Удобно, что после уроков есть тесты и вебинары.', 'Материал объяснён спокойно и без опасных обещаний.'].map((t,i)=><Card key={i} className="p-5"><p className="text-slate-700">“{t}”</p></Card>)}</div></div><div><h2 className="text-3xl font-bold">FAQ</h2><div className="mt-6 space-y-4">{[['Подходит ли для новичков?','Да, каждая программа стартует с базовых понятий.'],['Есть ли обещания доходности?','Нет. Мы обучаем принятию решений, а не даём торговые сигналы.'],['Можно ли учиться с телефона?','Да, весь сайт полностью адаптивен.']].map(([q,a]) => <Card key={q} className="p-5"><p className="font-semibold">{q}</p><p className="mt-2 text-sm text-slate-600">{a}</p></Card>)}</div></div></div></section>
    <section className="section bg-white"><div className="container-page grid gap-6 md:grid-cols-2 lg:grid-cols-3">{webinars.map((w)=><Card key={w.id} className="p-6"><p className="text-sm text-blue-600">{new Date(w.date).toLocaleDateString('ru-RU')}</p><h3 className="mt-2 text-xl font-semibold">{w.title}</h3><p className="mt-2 text-slate-600">{w.description}</p></Card>)}{articles.map((a)=><Card key={a.id} className="p-6"><p className="text-sm text-emerald-600">{a.category}</p><h3 className="mt-2 text-xl font-semibold">{a.title}</h3><p className="mt-2 text-slate-600">{a.excerpt}</p></Card>)}</div></section>
  </>;
}
